version: '3'
services:
  app:
    build: .
    command: sh -c "npm install && npm run start"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules: