version: '3'
services:
  app:
    build: .
    command: sh -c "ng serve --host 20.115.58.35"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 42389:42389
    expose:
      - 42389
volumes:
  node_modules: